FROM mambaorg/micromamba:2.0.5

USER root
RUN apt-get update \
    && apt-get install --yes --no-install-recommends procps \
    && rm -rf /var/lib/apt/lists/*

RUN micromamba install --yes --name base --channel conda-forge --channel bioconda \
        busco=5.8.2 \
        busco_phylogenomics \
        ete3 \
    && micromamba clean --all --yes

USER $MAMBA_USER